export const CATEGORIES = [
  { id: "electronics", nameKey: "electronics", icon: "📱" },
  { id: "vehicles", nameKey: "vehicles", icon: "🚗" },
  { id: "property", nameKey: "property", icon: "🏠" },
  { id: "furniture", nameKey: "furniture", icon: "🛋️" },
  { id: "fashion", nameKey: "fashion", icon: "👕" },
  { id: "beauty", nameKey: "beauty", icon: "💄" },
  { id: "baby", nameKey: "baby", icon: "👶" },
  { id: "sports", nameKey: "sports", icon: "⚽" },
  { id: "hobbies", nameKey: "hobbies", icon: "🎸" },
  { id: "pets", nameKey: "pets", icon: "🐕" },
  { id: "agriculture", nameKey: "agriculture", icon: "🌾" },
  { id: "industrial", nameKey: "industrial", icon: "🏭" },
  { id: "services", nameKey: "services", icon: "🛠️" },
  { id: "jobs", nameKey: "jobs", icon: "💼" },
  { id: "education", nameKey: "education", icon: "📚" },
  { id: "events", nameKey: "events", icon: "🎫" },
  { id: "food", nameKey: "food", icon: "🍔" },
  { id: "other", nameKey: "other", icon: "📦" },
];